//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        public System.Guid Oid { get; set; }
        public string O_Account { get; set; }
        public System.Guid O_Pid { get; set; }
        [DisplayName("訂單時間")]
        public string Date { get; set; }
        [DisplayName("數量")]
        public int Num { get; set; }
        [DisplayName("小計")]
        public int Sum { get; set; }
        [DisplayName("結帳")]
        public int Payed { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
